### PR TITLE
Fix contraction

### PR DESCRIPTION
**Pull request by tylertreat-wf**
Fixes a bug where branch contraction was not happening correctly, which was causing infinite loops in some cases.

@stevenosborne-wf @tylerrinnan-wf @brianshannan-wf @wesleybalvanz-wf @jacobmoss-wf 

FYI @alexandercampbell-wf @tayloranderson-wf

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1
but I don't know much about Ctries :)

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by tylerrinnan-wf** [comment]
+1

**Pull request merged**
