### PR TITLE
Simple Map Impl

### PR DESCRIPTION
**Pull request by alexandercampbell-wf**
### Code Review

Add a naive Matchbox implementation using a simple map + lock. We can use this for A/B testing against the Ctrie, since they both satisfy the same interface.

The performance of this Matchbox is likely to be significantly worse, so it's just for diagnostics.

```go
naive := matchbox.NewNaive()
```

### Reviewers

@tylertreat-wf @tylerrinnan-wf @dustinhiatt-wf @travissanderson-wf

### CODE REVIEW

**Comment by tylertreat-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by teresarevious-wf** [comment]
@rosie run_merge_script

**Comment by teresarevious-wf** [comment]
@rosie run_merge_script

**Pull request merged**
